package gui.mediator;

public enum Events {
    NEW_TAB,OPEN_MENU,CLOSE_MENU,UNDO_TEXT,REDO_TEXT
    ,ABOUT_MENU,SAVE_MENU,TEXT_CHANGED,SAVE_FILE,AUTO_SAVE,
    EXIT_EVENT, TAB_CHANGED, SAVE_REQUEST,
    COPY_MENU, CUT_MENU, PASTE_MENU, SHOW_FIND_REPLACE, SHOW_FIND, HIDE_REPLACE, FIND_SELECT, FIND_NEXT, FIND_PREVIOUS, REPLACE_CURRENT, REPLACE_ALL
}