package gui.mediator;

public enum Events {
    NEW_TAB,OPEN_MENU,CLOSE_MENU,UNDO_TEXT,REDO_TEXT
    ,ABOUT_MENU,SAVE_MENU,TEXT_CHANGED,SAVE_FILE,AUTO_SAVE,
    EXIT_EVENT, TAB_CHANGED, SAVE_REQUEST,
    COPY_MENU, CUT_MENU, PASTE_MENU, TOGGLE_FIND_REPLACE, TOGGLE_FIND, FIND_SELECT, FIND_NEXT, FIND_PREVIOUS, REPLACE_CURRENT, REPLACE_ALL
}